### ISSUE TITLE
undefined method in resume

### ISSUE THREAD

**Issue by swills** [rtyler/blimpy#45]
Hi,

I'm using blimpy with Ruby 1.9 and when I run blimpy start after adding a new ship, I get this:

> > Resuming: ,/usr/local/lib/ruby/gems/1.9/gems/blimpy-0.4.3/lib/blimpy/fleet.rb:61:in `block in resume': undefined method`resume' for nil:NilClass (NoMethodError)

Is this a ruby 1.9 issue or a more general bug?

Thanks,
Steve

**Comment by rtyler** [comment]
Interesting, I do all of my development and integration testing on 1.9, so I don't think that is it.

Did you add a new ship entry to the Blimpfile and then execute `blimpy resume`?

**Comment by swills** [comment]
Finally coming back to this... when I run "blimpy resume", I get "Could not find task "resume"." What am I missing?

Thanks,
Steve

**Comment by rtyler** [comment]
I'm going to close this since there isn't "resume" support explicitly in the CLI.

I'll create a new ticket to request that functionality. (issue #57)

**Comment by rtyler** [comment]
This work is complete.

(_This message brought to you by [Hub board](http://hubboard.herokuapp.com/about)_)
