### ISSUE TITLE
Need a way to instantiate w/o bootstrap

### ISSUE THREAD

**Issue by jblaine** [rtyler/blimpy#68]
A feature request because I just now commented out `host.bootstrap` from "blimpy start" to allow myself a 2-stage setup (start instances, which gets me their hostnames... then provision the livery which has Puppet modules referencing those hostnames).

"Chicken and egg" thing.

I'm not sure, if this is something you want to add, how you would want it done.

**Comment by rtyler** [comment]
Perhaps this should be something that can be overwritten in the `Blimpfile`? E.g.:

``` ruby
Blimpy.fleet do |f|
  f.add(:aws) do |ship|
    ship.name = 'test-host'
    # Option 1
    ship.disable_bootstrap = true
    # Option 2
    ship.provision_onboot = false
    # Option 3
    ship.disable_bootstrap!
  end

  # Option 4 (apply to all ships?)
  f.disable_bootstrap = true
end

```

**Comment by jblaine** [comment]
The fleet-level setting suits my use case the cleanest, though the ship-level setting is more flexible for other use cases so is probably preferable?

My vote for the name is `.provision_onstart` because it matches the blimpy top commands "provision" and "start"

(That aside, I have previous baggage (bikeshed-ish alert) that makes me dislike that the blimpy command "start" actually means "start and provision" when there's a separate "provision" command. That is, IMO, start should be start, provision should be provision, and "start + provision" should be something else like "bootstrap".)

**Comment by rtyler** [comment]
This was already taken care of with `host.provision_on_start = [bool]`
